# appveyor.yml

version: '{build}'
image: Visual Studio 2019

environment:
  matrix:
    - PYTHON: "C:\\Python39"

before_build:
  # Download and install Python
  - ps: |
      $url = 'https://www.python.org/ftp/python/3.9.6/python-3.9.6-amd64.exe'
      $outfile = 'python-3.9.6-amd64.exe'
      Invoke-WebRequest $url -OutFile $outfile
      Start-Process -Wait -FilePath $outfile -ArgumentList '/quiet', 'InstallAllUsers=1', 'PrependPath=1', 'Include_test=0'
      Remove-Item -Path $outfile

  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python --version
  - pip install --upgrade pip
  - pip install numpy matplotlib pybullet opencv-python click
  - pip install tensorflow-gpu==1.9.0

  # Install DART from source
  - git clone --depth 1 --branch v6.2.1 https://github.com/dartsim/dart.git
  - cd dart
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --config Release --target install
  - cd ../..

  # Install Flappy package
  - git clone https://github.com/purdue-biorobotics/flappy.git
  - cd flappy
  - pip install -e .
  - cd ..

build_script:
  - python flappy.py
